
package menus;

import java.awt.Color;
import javax.swing.ImageIcon;

public class materias extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public static int materias;
    
    public materias() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlCalDIf = new javax.swing.JPanel();
        btnCalDif = new javax.swing.JLabel();
        pnlFis = new javax.swing.JPanel();
        btnFis = new javax.swing.JLabel();
        pnlQuim = new javax.swing.JPanel();
        btnQuim = new javax.swing.JLabel();
        pnlCalFin = new javax.swing.JPanel();
        btnCalFin = new javax.swing.JLabel();
        imgCecyt14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(80, 0, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cecyt.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 570, -1));

        pnlCalDIf.setBackground(new java.awt.Color(71, 1, 36));
        pnlCalDIf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCalDif.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCalDif.setForeground(new java.awt.Color(255, 255, 255));
        btnCalDif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCalDif.setText("Cálculo Diferencial");
        btnCalDif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalDif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalDifMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCalDIfLayout = new javax.swing.GroupLayout(pnlCalDIf);
        pnlCalDIf.setLayout(pnlCalDIfLayout);
        pnlCalDIfLayout.setHorizontalGroup(
            pnlCalDIfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalDif, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        pnlCalDIfLayout.setVerticalGroup(
            pnlCalDIfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalDif, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(pnlCalDIf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 230, -1));

        pnlFis.setBackground(new java.awt.Color(71, 1, 36));

        btnFis.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFis.setForeground(new java.awt.Color(255, 255, 255));
        btnFis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFis.setText("Fisica");
        btnFis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlFisLayout = new javax.swing.GroupLayout(pnlFis);
        pnlFis.setLayout(pnlFisLayout);
        pnlFisLayout.setHorizontalGroup(
            pnlFisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        pnlFisLayout.setVerticalGroup(
            pnlFisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFis, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(pnlFis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, -1));

        pnlQuim.setBackground(new java.awt.Color(71, 1, 36));

        btnQuim.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnQuim.setForeground(new java.awt.Color(255, 255, 255));
        btnQuim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuim.setText("Quimica");
        btnQuim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlQuimLayout = new javax.swing.GroupLayout(pnlQuim);
        pnlQuim.setLayout(pnlQuimLayout);
        pnlQuimLayout.setHorizontalGroup(
            pnlQuimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuim, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        pnlQuimLayout.setVerticalGroup(
            pnlQuimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuim, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(pnlQuim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, 230, -1));

        pnlCalFin.setBackground(new java.awt.Color(71, 1, 36));

        btnCalFin.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCalFin.setForeground(new java.awt.Color(255, 255, 255));
        btnCalFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCalFin.setText("Calculos Financieros");
        btnCalFin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalFinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCalFinLayout = new javax.swing.GroupLayout(pnlCalFin);
        pnlCalFin.setLayout(pnlCalFinLayout);
        pnlCalFinLayout.setHorizontalGroup(
            pnlCalFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalFin, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        pnlCalFinLayout.setVerticalGroup(
            pnlCalFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalFin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(pnlCalFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 344, 230, -1));

        imgCecyt14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel2.add(imgCecyt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 55, -1, -1));

        jPanel4.setBackground(new java.awt.Color(80, 0, 40));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(80, 0, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalDifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalDifMouseClicked
        materias=1;
        
        Parcial abrir = new Parcial();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCalDifMouseClicked

    private void btnFisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFisMouseClicked
        materias=2;
        
        Parcial abrir = new Parcial();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFisMouseClicked

    private void btnQuimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuimMouseClicked
        materias=3;
        
        Parcial abrir = new Parcial();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuimMouseClicked

    private void btnCalFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalFinMouseClicked
        materias=4;
        
        Parcial abrir = new Parcial();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCalFinMouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jPanel5.setBackground(Color.red);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jPanel5.setBackground(new Color(80,0,40));
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new materias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnCalDif;
    private javax.swing.JLabel btnCalFin;
    private javax.swing.JLabel btnFis;
    private javax.swing.JLabel btnQuim;
    private javax.swing.JLabel imgCecyt14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnlCalDIf;
    private javax.swing.JPanel pnlCalFin;
    private javax.swing.JPanel pnlFis;
    private javax.swing.JPanel pnlQuim;
    // End of variables declaration//GEN-END:variables
}
